version: '3.4'

services:
  apimongodbexperiment.api:
    container_name: apimongodbexperimentapi
    image: ${DOCKER_REGISTRY-}apimongodbexperimentapi
    build:
      context: .
      dockerfile: ApiMongoDbExperiment.API/Dockerfile
    environment:
      - "MongoDb__ConnectionString=mongodb://admin:password@mongo:27017"
      - "MongoDb__Database=MasterLeague"
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
